### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by qindan2008** [zju3351689/rklib#1]
Hi,
I tried to install rklib under python3, some errors occurred:
 Compiling rklib/compress.pyx because it changed.
Compiling rklib/fmtprint.pyx because it changed.
Compiling rklib/googletr.pyx because it changed.
Compiling rklib/log.pyx because it changed.
Compiling rklib/mhtml.pyx because it changed.
Compiling rklib/mhtml_v4.pyx because it changed.
Compiling rklib/mp.pyx because it changed.
Compiling rklib/plot_kegg.pyx because it changed.
Compiling rklib/progress_bar.pyx because it changed.
Compiling rklib/send_email.pyx because it changed.
Compiling rklib/test.pyx because it changed.
Compiling rklib/threads.pyx because it changed.
Compiling rklib/utils.pyx because it changed.
[ 1/13] Cythonizing rklib/compress.pyx
[ 2/13] Cythonizing rklib/fmtprint.pyx
[ 3/13] Cythonizing rklib/googletr.pyx
[ 4/13] Cythonizing rklib/log.pyx
[ 5/13] Cythonizing rklib/mhtml.pyx
[ 6/13] Cythonizing rklib/mhtml_v4.pyx
[ 7/13] Cythonizing rklib/mp.pyx
[ 8/13] Cythonizing rklib/plot_kegg.pyx
[ 9/13] Cythonizing rklib/progress_bar.pyx
[10/13] Cythonizing rklib/send_email.pyx
[11/13] Cythonizing rklib/test.pyx

Error compiling Cython file:
------------------------------------------------------------
...
# -*- coding: UTF-8 -*-
import sys
import time
import utils
utils.monitor_controlC()
print "中文"
     ^
------------------------------------------------------------

rklib/test.pyx:6:6: Syntax error in simple statement list
Traceback (most recent call last):
  File "./setup.py", line 31, in <module>
    'ext_modules': cythonize("*/*.pyx",language_level=3),
  File "/usr/local/lib/python3.8/dist-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.8/dist-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: rklib/test.pyx

How to fixed it?
Thank you.

**Comment by Drgrass** [comment]
Do you solve it? I also confused about it.

**Comment by JHwarlock** [comment]
I'm really sorry for the late reply. We have re-released version 2.1.3, and this problem should be solved

**Comment by JHwarlock** [comment]
error solved by v2.1.3

**Comment by Drgrass** [comment]
Thanks a lot!

**Comment by Drgrass** [comment]
Dr.Rong,
&nbsp; &nbsp; 您好！我是中山大学21级博士，临床专业的，因为课题需要计算CIN，在网上找到您的代码，研究了好久。花了大半个月研究这个代码，自己一行一行代码看，解决了很多报错，但现在存在一个报错，实在解决不了，希望能够得到指导一下。有偿也可。感谢老师。我的手机号：15955265552
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;附件中的数据是从https://wiki.basepedia.com/doku.php?id=%E5%85%AC%E5%85%B1:software:cincalc复制来的。
问题是，1. 在MAC终端里，python CINcalc.py cnvfile -r chrfile&nbsp;，总出现&nbsp;TypeError: must be real number, not tuple

(base) ***@***.*** CIN % python CINcalc.py cnvfile -r chrfile&nbsp;

{'TCGA-OR-A5LA-01A': [['chr1', 3301765, 5128894, 1.719870572335768, 1.719870572335768, 1.719870572335768], ['chr1', 5132643, 47878718, 1.7666301029629303, 1.7666301029629303, 1.7666301029629303], ['chr1', 47879273, 109220206, 1.692434499755176, 1.692434499755176, 1.692434499755176], ['chr1', 109223247, 161957073, 1.749205754879355, 1.749205754879355, 1.749205754879355]]}

#SN	wploidy	wgii

Traceback (most recent call last):

&nbsp; File "/Users/chm/Documents/Urological_doctor/graduate_thesis/CIN/CINcalc.py", line 94, in <module&gt;

&nbsp; &nbsp; ret&nbsp; &nbsp; &nbsp; &nbsp; = __main()

&nbsp; File "/Users/chm/Documents/Urological_doctor/graduate_thesis/CIN/CINcalc.py", line 88, in __main

&nbsp; &nbsp; ret = runscript(cnvfile,chrfile,ploidy,upcut,lowcut)

&nbsp; File "/Users/chm/Documents/Urological_doctor/graduate_thesis/CIN/CINcalc.py", line 47, in runscript

&nbsp; &nbsp; sys.stdout.write("%s\t%.5f\t%.5f\n"%(sn,wploidy,wgii))

TypeError: must be real number, not tuple

&nbsp;
&nbsp;2. 所以我用Spyder软件，打开代码，一行行看，发现是&nbsp;wgii&nbsp; &nbsp; = cin_ins.wgii(tgain=2**upcut * ploidy,tloss=2**lowcut * ploidy,chrlen=hchr,numchrs=len(hchr)), 计算出的wgii是元组，而不是一个数值？

学生：曹海明
2022-06-16 夜1:15






------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Jun 13, 2022 04:20 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [JHwarlock/rklib] install error (Issue #1)

&nbsp;



 
solved
